### PR TITLE
Remove all files to get empty directory

### PR DESCRIPTION
**Pull request by nikhita**
This is necessary to make sure that the publishing bot does not encounter any conflicts while syncing with
staging.

Ref: https://github.com/kubernetes/kubernetes/tree/master/staging#creating-the-published-repository

Related: https://github.com/kubernetes/publishing-bot/pull/118

/cc @sttts @spiffxp @yliaog

### CODE REVIEW

**Comment by nikhita** [comment]
We will need magical powers to merge this. :)

**Comment by nikhita** [comment]
@spiffxp can you also add the permissions as mentioned in https://github.com/kubernetes/org/issues/56#issue-356711512?

**Comment by nikhita** [comment]
cc @cblecker 

because github-management stuff

**Comment by spiffxp** [comment]
Manually merging, OWNERS file is using a non-existent alias, so nobody can /approve

**Pull request merged**
